# Question

The component below makes a mistake when using `useEffect`. When running this code, we will get an error from React!

What is the mistake? Also, please demonstrate how to properly fetch by fixing this code.

```js
const DogDisplay = () => {
  const [imgSrc, setImgSrc] = useState(
    'https://images.dog.ceo/breeds/hound-english/n02089973_612.jpg'
  );

  useEffect(async () => {
    try {
      const response = await fetch('https://dog.ceo/api/breeds/image/random');
      if (!response.ok) throw new Error(`Error: ${response.status}`);
      const data = await response.json();
      setImgSrc(data.message);
    } catch (error) {
      console.error(error);
    }
  }, []);

  return <img src={imgSrc} />;
};
```

# Answer

I believe the issue stems from the usage of `async`. `useEffect` is not built with using asynchronous functions in mind so an error would pop up when doing so. A solution could be using Promises in a different way, which is with `.then()` and `.catch()` instead like the following:

```js
const DogDisplay = () => {
  const [imgSrc, setImgSrc] = useState(
    'https://images.dog.ceo/breeds/hound-english/n02089973_612.jpg'
  );

  useEffect(() => {
    fetch('https://dog.ceo/api/breeds/image/random')
      .then((response) => {
        if (!response.ok) {
          throw new Error(`Error: ${response.status}`);
        }
        return response.json();
      })
      .then((data) => {
        setImgSrc(data.message);
      })
      .catch((error) => {
        console.error(error);
      });
  }, []);

  return <img src={imgSrc} alt="A random dog" />;
};
```

# Teacher Feedback
1/3
Great job on identifying that async is not suitable directly inside useEffect and providing a working solution with .then() and .catch(). However, we were actually looking for the approach of defining an inner async function within useEffect and calling it immediately. This method avoids potential issues and maintains cleaner code.